title:             migaman.org
email:             mikee@bluewin.ch
description:       A Blog by migaman
author:            migaman
baseurl:           "/"
url:               "http://migaman.org"

# Build settings
markdown:          kramdown
plugins:
 - jekyll-paginate-v2

 
# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  
# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:title.html
