title:             Migaman
email:             mikee@bluewin.ch
description:       A Blog by Migaman
author:            Migaman
baseurl:           "/"
url:               "http://migaman.org"

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
 - jekyll-paginate

